/*
* Generated file
*
* Generated from: yang module name: ping-provider-impl yang module local name: ping-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Apr 01 16:24:36 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.ping_provider.impl;
public class PingProviderModuleFactory extends org.opendaylight.controller.config.yang.config.ping_provider.impl.AbstractPingProviderModuleFactory {

}
